SELECT * FROM TBL_FORNECEDOR;
SELECT * FROM TBL_PECA;
SELECT * FROM TBL_INSTITUICAO;
SELECT * FROM TBL_PROJETO;
SELECT * FROM TBL_FORNECIMENTO;
DROP TABLE TBL_PROJETO;
ALTER TABLE TBL_PROJETO
	DROP prcodigo CASCADE
	ALTER TABLE TBL_PROJETO
	DROP COLUMN ICOD;
	DROP TABLE TBL_INSTITUICAO;
	CREATE TABLE TBL_CIDADE(
CCOD INT NOT NULL,
CNOME VARCHAR(30) NOT NULL,
UF CHAR(2) NOT NULL,
PRIMARY KEY (CCOD)
);
SELECT * FROM TBL_CIDADE;
ALTER TABLE TBL_FORNECEDOR
	DROP COLUMN FCIDADE;

ALTER TABLE TBL_FORNECEDOR
	ADD FONE BIGINT NOT NULL;

ALTER TABLE TBL_FORNECEDOR
	ADD CCOD INT NOT NULL;

ALTER TABLE TBL_FORNECEDOR
	ADD CONSTRAINT FK_CCOD_FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);


SELECT * FROM TBL_FORNECEDOR;

ALTER TABLE TBL_PECA
	DROP COLUMN PCIDADE;

ALTER TABLE TBL_PECA 
	ADD CCOD INT NOT NULL;

ALTER TABLE TBL_PECA
	ADD CONSTRAINT FK_CCOD_PECA
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);

ALTER TABLE TBL_PROJETO
	DROP COLUMN CIDADE;

ALTER TABLE TBL_PROJETO
	ADD CCOD INT NOT NULL;

ALTER TABLE TBL_PROJETO
	ADD CONSTRAINT FK_CCOD_PROJETO
    FOREIGN KEY (CCOD) REFERENCES TBL_CIDADE (CCOD);
CREATE INDEX IDX_CCOD_FOR ON TBL_FORNECEDOR(CCOD);
CREATE INDEX IDX_CCOD_PEC ON TBL_PECA(CCOD);
CREATE INDEX IDX_CCOD_PRO ON TBL_PROJETO(CCOD);

ALTER TABLE TBL_EMPRESA
DROP CONSTRAINT ICODIGO;

INSERT INTO tbl_cidade 
VALUES (11,'Limeira', 'SP');
VALUES (12,'São Paulo', 'SP');
VALUES (13,'Rio Claro', 'SP');
VALUES (14,'Piracicaba', 'SP');


INSERT INTO tbl_fornecedor 
VALUES (01,'Kalunga', 'Ativo', '1930234066');
VALUES (12,'São Paulo', 'SP');
VALUES (13,'Rio Claro', 'SP');
VALUES (14,'Piracicaba', 'SP');
































